name: Run tox tests

on: [pull_request]

jobs:
  python-tox-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - 'python 3.10'
          - 'python 3.9'
          - 'python 3.8'
          - 'python 3.7'
          - 'python 3.6'
          - 'sanity-checks'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.X
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.component }}

      - name: Install dependencies
        if: ${{ matrix.additional_packages }}
        run: |
          sudo apt-get update && sudo apt-get install -y ${{ matrix.additional_packages }}

      - name: Install tox/wheel/setuptools
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools tox

      - name: List tox environments
        run: |
          # runs tox
          tox -l

      - name: Install dependencies from tox
        timeout-minutes: 15
        run: |
          # runs tox with exhaustive package installation
          tox -e ${{ matrix.component }} --notest -vv

      - name: Run tests from tox
        timeout-minutes: 30
        run: |
          # runs tox
          tox -l
          tox -e ${{ matrix.component }}

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Tox test results (${{ matrix.component }})
          path: ${{ github.workspace }}/.tox/**/tmp/*.xml

  publish-test-results:
    name: 'publish unit tests results'
    needs: [python-tox-tests]
    runs-on: ubuntu-latest
    # previous jobs might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: artifacts/**/*.xml
